openapi: 3.0.3
info:
  title: Endpoint of Bank Registry
  version: v1
paths:

  /banks:
    get:
      tags:
        - bank
      summary: Returns a list of banks.
      responses:
        "200":
          description: A JSON array of banks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Bank"
        "204":
          description: no banks found
    post:
      tags:
        - bank
      summary: Create bank
      description: This can only be done by the logged in user.
      operationId: createBank
      requestBody:
        description: Created bank object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bank'
      responses:
        "201":
          description: bank created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bank'
        "409":
          description: bank already exist



components:

  schemas:
    Bank:
      required:
        - name
        - countrycode
        - checkdigits
        - bankcode
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        name:
          type: string
          minLength: 1
          maxLength: 20
          pattern: '\p{L}+'
          example: EX Bank
        countrycode:
          type: string
          pattern: '\p{L}\p{L}'
          example: DE
        checkdigits:
          type: integer
          format: int64
          minLength: 2
          maxLength: 2
          example: 19
        bankcode:
          type: integer
          format: int64
          minLength: 8
          maxLength: 8
          example: 11111111
        description:
          type: string
          example: This is a new bank
        dateOfCreation:
          type: string
          format: date-time
          readOnly: true







